# SETTINGS
import math
# GENERAL
WIDTH, HEIGHT = 1600, 900

FPS = 60

#  MAP/TILES

TILE_SIZE_2D = 100
TEXTURE_SIZE = 128

# PLAYER

PLAYER_X = 5
PLAYER_Y = 2.5
PLAYER_SPEED = 0.05
PLAYER_ANGLE_SPEED = 0.008
PLAYER_SIZE = 5

MOUSE_MAX_LEFT = 200
MOUSE_MAX_RIGHT = WIDTH -100
MOUSE_MAX_MOVE = 10

# RAYTRACING
FOV = math.pi / 3 # FOV = 60 = pi/3
RAYS_NUMBER = WIDTH//2
RAY_MAX_LENGTH = 20
RAY_DELTA_ANGLE = FOV / RAYS_NUMBER
SCALE = WIDTH/RAYS_NUMBER